display_name: dropweb

packager: dropweb
packagerEmail: info@dropweb.org
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - dropweb
  - Clash
    - Proxy

generic_name: dropweb

group: Applications/Internet

startup_notify: true