display_name: dropweb
package_name: dropweb
maintainer:
  name: dropweb
  email: info@dropweb.org

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - dropweb
  - Clash
  - ClashMeta
  - Proxy

generic_name: dropweb

categories:
  - Network

startup_notify: true